2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Configure stats pid to 26360
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Loading settings from C:\Users\zaynm\.config\wandb\settings
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Loading settings from d:\AiProjects\PneumoniaClassifier\wandb\settings
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-04 17:41:58,590 INFO    MainThread:26360 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-04 17:41:58,591 INFO    MainThread:26360 [wandb_init.py:_log_setup():534] Logging user logs to d:\AiProjects\PneumoniaClassifier\wandb\run-20241104_174158-i0tye67j\logs\debug.log
2024-11-04 17:41:58,591 INFO    MainThread:26360 [wandb_init.py:_log_setup():535] Logging internal logs to d:\AiProjects\PneumoniaClassifier\wandb\run-20241104_174158-i0tye67j\logs\debug-internal.log
2024-11-04 17:41:58,591 INFO    MainThread:26360 [wandb_init.py:init():621] calling init triggers
2024-11-04 17:41:58,591 INFO    MainThread:26360 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {}
2024-11-04 17:41:58,591 INFO    MainThread:26360 [wandb_init.py:init():646] re-initializing run, found existing run on stack: pfqj987c
2024-11-04 17:41:58,592 INFO    MainThread:26360 [wandb_run.py:_finish():2158] finishing run zheng-yu3-ucl/chest_xray_classification/pfqj987c
2024-11-04 17:41:58,593 ERROR   MainThread:26360 [jupyter.py:save_history():451] Run pip install nbformat to save notebook history
2024-11-04 17:41:58,593 INFO    MainThread:26360 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2024-11-04 17:41:58,593 INFO    MainThread:26360 [wandb_init.py:_jupyter_teardown():462] cleaning up jupyter logic
2024-11-04 17:41:58,593 INFO    MainThread:26360 [wandb_run.py:_atexit_cleanup():2426] got exitcode: 0
2024-11-04 17:41:58,593 INFO    MainThread:26360 [wandb_run.py:_restore():2408] restore
2024-11-04 17:41:58,593 INFO    MainThread:26360 [wandb_run.py:_restore():2414] restore done
2024-11-04 17:42:32,822 WARNING MainThread:26360 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 656, in init
    latest_run.finish()
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 452, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2151, in finish
    return self._finish(exit_code, quiet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2185, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2438, in _atexit_cleanup
    self._on_finish()
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2688, in _on_finish
    _ = exit_handle.wait(
        ^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zaynm\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
